spring:
  datasource:
      url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
      username: root
      password: 123456
mybatis:
   mapperLocations: classpath:/mapper/*.xml
